# Generated by Django 4.0.5 on 2022-06-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_todolist_todoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='todo_list',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='type',
            field=models.CharField(default='Default', max_length=25),
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
