# Generated by Django 4.0.5 on 2022-06-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_remove_todoitem_todo_list_todoitem_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='details',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
